# Generated by Django 4.0.4 on 2022-05-10 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_appuser_email_alter_appuser_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='email_confirmend',
            new_name='email_confirmed',
        ),
    ]
