# Generated by Django 4.0.4 on 2022-05-15 17:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_rename_email_confirmend_appuser_email_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='last_email_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
